version: "3"

networks:
  webnet:
    driver: bridge

services:

  sut:
    build: ci_build_test
    depends_on:
      - web
    networks:
      - webnet

  web:
    build: .
    networks:
      - webnet