version: "3"

#########################################################
####               Simple Web Server                 ####
#########################################################

#########################################################
####                   Networking                    ####
#########################################################
networks:
  webnet:
    driver: bridge

#########################################################
####                   Services                      ####
#########################################################
services:

  web:
    image: balluff/simplewebserver
    container_name: sws
    restart: always
    ports:
      - "3000:3000"
    networks:
      - webnet