# Use the Alpine base image
FROM alpine:3.8

# Some information
LABEL Maintainer "Andreas Elser"
LABEL Version "0.1"
LABEL Name "Balluff Docker Cloud Testing"

# Install curl
RUN apk add --no-cache curl

# Change the work directory
WORKDIR /app

# Copy the testing script and make it executable
ADD test.sh /app/test.sh
RUN chmod +x test.sh

# Run the test script
CMD [ "/app/test.sh" ]